export const userList = [
  "Prof. Yuan",
  "Guozheng Li",
  "Shuai Chen",
  "Chenglei Yue",
  "Ruike Jiang",
  "Can Liu",
  "Jincheng Li",
  "Chaofan Yang",
  "Hanning Shao",
  "Yuchu Luo",
  "Zhixian Lin",
  "Min Tian",
  "Dingyi Yang",
  "Changhe Yang",
  "Yanda Li",
  "Datong Wei",
  "Cong Wu",
  "Hao Wu",
  "Shaocong Tan",
  "Jiacheng Yu",
  "Sihang Li",
  "Zhen Li",
  "Haohua Liu",
];

export default userList;
